/* One command registry powers the menu bar, shortcuts and desktop search. */
(function (global, $) {
'use strict';
class MacMenus {
 constructor(wm,workspace,store) {
  this.wm=wm; this.workspace=workspace; this.store=store; this.panel=null; this.context=null; this.month=new Date();
  this.lastContext=null; document.addEventListener('focusout',e=>{if(e.target?.matches?.('input,textarea')&&!e.target.closest('.menu-panel'))this.lastContext={record:this.wm.activeWindow,element:e.target,start:e.target.selectionStart,end:e.target.selectionEnd};}); document.addEventListener('focusin',e=>{if(!e.target.closest('#menubar,.menu-panel'))this.lastContext=this.capture();});
  this.names=['Apple','Application','File','Edit','View','Go','Window','Help'];
  const left=document.querySelector('#menubar .menu-left'); const right=document.querySelector('#menubar .menu-right');
  left.replaceChildren(); right.replaceChildren();
  this.buttons=this.names.map(name=>{const b=this.button(name==='Apple'?'●':name,()=>{const context=this.pendingContext||this.lastContext||this.capture();this.pendingContext=null;this.openMenu(name,b,context);}); b.dataset.menu=name;b.setAttribute('aria-haspopup','menu');b.setAttribute('aria-expanded','false');b.addEventListener('pointerdown',()=>{this.pendingContext=this.panel?this.context:this.capture();});b.addEventListener('keydown',e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();this.openMenu(name,b,this.lastContext||this.capture());}else if(!this.panel&&(e.key==='ArrowLeft'||e.key==='ArrowRight')){e.preventDefault();this.buttons[(this.names.indexOf(name)+(e.key==='ArrowRight'?1:-1)+this.names.length)%this.names.length].focus();}});left.append(b);return b;});
  this.buttons[0].setAttribute('aria-label','Apple'); this.buttons[1].id='active-app-name'; this.buttons[2].id='file-menu-button';
  for(const [name,label] of [['battery','Battery'],['network','Network'],['search','Search'],['control','Control Center'],['clock','Clock']]) { const b=this.button(label,()=>this.openStatus(name,b));b.dataset.status=name;b.setAttribute('aria-label',label);b.setAttribute('aria-expanded','false');right.append(b); }
  this.clock=right.querySelector('[data-status="clock"]');this.updateClock();this.clockTimer=setInterval(()=>this.updateClock(),1000);
  wm.subscribe?.(()=>this.update());this.update();
  document.addEventListener('pointerdown',e=>{if(this.panel&&!this.panel.contains(e.target)&&!e.target.closest('#menubar'))this.close();});
  document.addEventListener('keydown',e=>this.keydown(e));
  global.addEventListener('online',()=>this.refreshNetwork());global.addEventListener('offline',()=>this.refreshNetwork());
  store.subscribe(()=>{if(this.panel?.classList.contains('spotlight'))this.search(this.panel.querySelector('input').value);});
 }
 button(label,run){const b=document.createElement('button');b.type='button';b.textContent=label;b.setAttribute('aria-label',label);b.addEventListener('click',run);return b;}
 update(){const name=this.wm.activeWindow?.name||'Finder';this.buttons[1].textContent=name;this.buttons[1].setAttribute('aria-label',name+' application menu');}
 updateClock(){this.clock.textContent=new Date().toLocaleString(undefined,{weekday:'short',hour:'numeric',minute:'2-digit',hour12:!this.wm.settings.clock24});}
 capture(){const el=document.activeElement;return {record:this.wm.activeWindow,element:el,start:typeof el.selectionStart==='number'?el.selectionStart:null,end:typeof el.selectionEnd==='number'?el.selectionEnd:null};}
 restore(context){if(!context?.element?.isConnected)return;context.element.focus({preventScroll:true});if(context.start!==null)try{context.element.setSelectionRange(context.start,context.end);}catch(_){}}
 close(restore=true){this.panelCleanup?.();this.panelCleanup=null;const context=this.context;this.panel?.remove();this.panel=null;this.context=null;document.querySelectorAll('#menubar [aria-expanded]').forEach(b=>b.setAttribute('aria-expanded','false'));if(restore)this.restore(context);}
 showPanel(anchor,className='desktop-menu',context){this.close(false);this.context=context||this.capture();const p=document.createElement('div');p.className='menu-panel '+className;p.setAttribute('role','menu');document.body.append(p);this.panel=p;this.anchor=anchor;anchor?.setAttribute('aria-expanded','true');const r=anchor?.getBoundingClientRect();p.style.top=(r?r.bottom+5:60)+'px';p.style.left=(r?Math.max(8,Math.min(r.left,innerWidth-330)):Math.max(8,(innerWidth-600)/2))+'px';return p;}
 controller(record){return record?.controller||this.workspace.desktopController||this.workspace.desktop;}
 descriptor(id,label,record){const controller=this.controller(record);const commands=controller?.commands||this.workspace.getCommands?.(record)||{};const c=commands[id];return {id,label:label||c?.label||id,enabled:()=>Boolean(c)&&(typeof c.enabled==='function'?c.enabled():c.enabled!==false),checked:c?.checked,run:()=>c?.run()};}
 registry(record,context){const d=(id,label)=>this.descriptor(id,label,record);const action=(id,label,run,enabled=true,checked)=>({id,label,run,enabled,checked});const app=record?.appId||'finder';const menu={};
  menu.Apple=[action('aboutDesktop','About This Desktop',()=>this.help('About This Desktop')),action('settings','System Settings…',()=>this.wm.openApp('settings')),action('restart','Restart Desktop…',()=>this.wm.restart())];
  menu.Application=[action('aboutApp','About '+(record?.name||'Finder'),()=>this.help('About '+(record?.name||'Finder'))),action('quit','Close All '+(record?.name||'Finder')+' Windows',()=>this.wm.closeApp(app),this.wm.listWindows().some(w=>w.appId===app))];
  const finder=[action('newFinder','New Finder Window',()=>this.wm.openApp('finder',{newWindow:true})),d('newFolder','New Folder'),d('newText','New Text File'),d('open','Open'),d('rename','Rename…'),d('getInfo','Get Info'),d('trash','Move to Trash'),d('emptyTrash','Empty Trash…')];
  menu.File=app==='textedit'?[d('newDocument','New Document'),d('save','Save'),d('saveAs','Save As…'),d('export','Export .txt')]:app==='terminal'?[action('newTerminal','New Terminal Window',()=>this.wm.openApp('terminal',{newWindow:true}))]:app==='safari'?[d('openLocation','Open Location…'),d('openExternal','Open Current Page Externally')]:app==='sketch'?[d('newDrawing','New Drawing'),d('importPNG','Import PNG…'),d('exportPNG','Export PNG')]:app==='trash'?[d('restore','Restore Selected Item'),d('emptyTrash','Empty Trash…')]:app==='finder'?finder:[];
  menu.File.push(action('close','Close Window',()=>this.wm.requestClose(record.id),Boolean(record)));
  menu.Edit=app==='sketch'?[d('undo','Undo'),d('redo','Redo'),d('clear','Clear Drawing')]:app==='calculator'?[d('copyResult','Copy Result')]:['undo','redo','cut','copy','paste','selectAll'].map(id=>action(id,({selectAll:'Select All'})[id]||id[0].toUpperCase()+id.slice(1),()=>this.edit(id,context),()=>this.canEdit(id,context)));
  menu.View=[action('showDesktop','Show Desktop',()=>this.wm.showDesktop()),action('overview','Window Overview',()=>this.wm.overview()),{id:'appearance',label:'Appearance',children:['dark','light','system'].map(value=>action('appearance-'+value,value[0].toUpperCase()+value.slice(1),()=>this.wm.updateSettings({appearance:value}),true,()=>this.wm.settings.appearance===value))}];
  if(['finder','trash'].includes(app)||!record)menu.View.push(d('sortName','Sort by Name'),d('sortType','Sort by Type'));
  if(app==='textedit')menu.View.push(d('font','Font…'),d('size','Font Size…'));
  menu.Go=['Desktop','Documents','Downloads'].map(folder=>action('go-'+folder,folder,()=>record?.appId==='finder'?record.controller.navigate([folder]):this.wm.openApp('finder',{path:[folder]})));menu.Go.push(action('go-Trash','Trash',()=>this.wm.openApp('trash')));
  if(app==='finder')menu.Go.push(d('back','Back'),d('forward','Forward'),d('up','Enclosing Folder'));
  if(app==='safari')menu.Go.push(d('back','Back'),d('forward','Forward'),d('home','Home'));
  if(['textedit','terminal'].includes(app))menu.Go.push(d('reveal','Reveal in Finder'));
  menu.Window=[action('minimize','Minimize',()=>this.wm.minimizeWindow(record.id),Boolean(record)),action('maximize',record?.maximized?'Restore':'Maximize',()=>this.wm.maximizeWindow(record.id),Boolean(record))];
  if(['finder','textedit','terminal'].includes(app))menu.Window.push(action('newWindow',app==='textedit'?'New Document':'New Window',()=>this.wm.openApp(app,{newWindow:true})));
  menu.Window.push(...this.wm.listWindows().map(w=>action('window-'+w.id,(w.minimized?'[Minimized] ':'')+(w.title||w.name),()=>this.wm.focusWindow(w.id),true,()=>record?.id===w.id)));
  menu.Help=['Desktop Guide','Keyboard Shortcuts','Storage & Browser Capabilities'].map(title=>action('help-'+title,title,()=>this.help(title)));
  return menu;
 }
 enabled(c){return typeof c.enabled==='function'?c.enabled():c.enabled!==false;}
 async execute(c,context){if(!this.enabled(c))return;this.close(false);this.restore(context);try{await c.run();}catch(e){this.workspace.report(e.message,true);}}
 openMenu(name,anchor,context){if(this.panel&&this.menuName===name&&this.panel.classList.contains('desktop-menu')){this.close();return;}context=context||this.capture();this.menuName=name;const panel=this.showPanel(anchor,'desktop-menu',context);this.renderItems(panel,this.registry(context.record,context)[name],context);panel.querySelector('button:not(:disabled)')?.focus();}
 renderItems(panel,items,context){items.forEach(c=>{const b=this.button(c.label,()=>{if(c.children){this.openSubmenu(b,c.children,context);return;}this.execute(c,context);});b.dataset.command=c.id;b.disabled=!this.enabled(c);const checked=typeof c.checked==='function'?c.checked():c.checked;if(c.checked!==undefined){b.setAttribute('role','menuitemcheckbox');b.setAttribute('aria-checked',String(Boolean(checked)));if(checked)b.textContent='✓ '+b.textContent;}else b.setAttribute('role','menuitem');if(c.children){b.textContent+='  ›';b.setAttribute('aria-haspopup','menu');b.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();e.stopPropagation();this.openSubmenu(b,c.children,context);}});}panel.append(b);});}
 openSubmenu(anchor,items,context){this.panel.querySelector('.submenu')?.remove();const p=document.createElement('div');p.className='submenu';p.setAttribute('role','menu');this.panel.append(p);this.renderItems(p,items,context);p.querySelector('button:enabled')?.focus();p.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();e.stopPropagation();p.remove();anchor.focus();}});}
 canEdit(id,context){const el=context?.element;const record=context?.record;if(el&&((record?.element&&!record.element.contains(el))||(!record&&el.closest?.('.window'))))return false;if(!el||!['INPUT','TEXTAREA'].includes(el.tagName)||el.disabled||el.readOnly||el.type==='file'||record?.appId==='safari'&&el.tagName==='IFRAME')return false;if(['copy','cut'].includes(id))return context.start!==context.end;if(['undo','redo'].includes(id)){const c=record?.controller?.commands?.[id];return c?(typeof c.enabled==='function'?c.enabled():c.enabled!==false):typeof document.execCommand==='function';}return true;}
 async edit(id,context){if(!this.canEdit(id,context))return;const el=context.element;const original=el.value;this.restore(context);const c=context.record?.controller?.commands?.[id];if(c&&['undo','redo'].includes(id)){await c.run();return;}if(id==='selectAll'){el.select();return;}if(['undo','redo'].includes(id)){if(!document.execCommand(id))this.workspace.report('No '+id+' is available for this field.');return;}try{if(!navigator.clipboard)throw new Error('Clipboard is unavailable in this browser or context.');if(id==='copy'||id==='cut'){await navigator.clipboard.writeText(el.value.slice(context.start,context.end));if(id==='copy')return;if(!el.isConnected||el.value!==original){this.workspace.report('Text changed while copying; nothing was removed.',true);return;}el.setRangeText('',context.start,context.end,'end');}else{const text=await navigator.clipboard.readText();if(!el.isConnected||el.value!==original){this.workspace.report('Text changed while reading the clipboard; paste was cancelled.',true);return;}el.setRangeText(text,context.start,context.end,'end');}el.dispatchEvent(new Event('input',{bubbles:true}));}catch(e){this.workspace.report('Clipboard action failed: '+e.message,true);}}
 keydown(e){if(document.querySelector('dialog[open]'))return;if(this.panel){if(e.key==='Escape'){e.preventDefault();this.close();return;}if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)&&!this.panel.classList.contains('spotlight')){e.preventDefault();const scope=e.target.closest?.('.submenu')||this.panel;const list=Array.from(scope.querySelectorAll(':scope > button:not(:disabled)'));let i=list.indexOf(document.activeElement);i=e.key==='Home'?0:e.key==='End'?list.length-1:(i+(e.key==='ArrowDown'?1:-1)+list.length)%list.length;list[i]?.focus();return;}if(['ArrowLeft','ArrowRight'].includes(e.key)&&this.names.includes(this.menuName)){e.preventDefault();const context=this.context;const index=(this.names.indexOf(this.menuName)+(e.key==='ArrowRight'?1:-1)+this.names.length)%this.names.length;this.menuName=null;this.openMenu(this.names[index],this.buttons[index],context);return;}}
  if((e.metaKey||e.ctrlKey)&&e.code==='Space'){e.preventDefault();this.spotlight();return;}if(e.key==='F3'){e.preventDefault();this.wm.overview();return;}if(!(e.metaKey||e.ctrlKey)||e.altKey)return;
  const key=e.key.toLowerCase();let id=key==='s'?(e.shiftKey?'saveAs':'save'):key==='w'?'close':key==='n'?(e.shiftKey?'newFolder':'newWindow'):null;if(!id)return;const context=this.capture();const registry=this.registry(context.record,context);const c=Object.values(registry).flat().find(item=>item.id===id);if(c&&this.enabled(c)){e.preventDefault();this.execute(c,context);}
 }
 openStatus(name,anchor){if(name==='search'){this.spotlight();return;}if(this.panel?.classList.contains('status-panel')&&this.statusName===name){this.close();this.statusName=null;return;}this.menuName=null;this.statusName=name;const p=this.showPanel(anchor,'status-panel');p.setAttribute('role','dialog');p.setAttribute('aria-label',anchor.getAttribute('aria-label'));const heading=document.createElement('h2');heading.textContent=anchor.getAttribute('aria-label');p.append(heading);
  if(name==='battery'){const text=document.createElement('p');text.textContent='Battery information unavailable in this browser.';p.append(text);if(navigator.getBattery)navigator.getBattery().then(b=>{if(!text.isConnected)return;const update=()=>{if(text.isConnected)text.textContent=Math.round(b.level*100)+'% · '+(b.charging?'Charging':'On battery');};update();b.addEventListener('levelchange',update);b.addEventListener('chargingchange',update);this.panelCleanup=()=>{b.removeEventListener('levelchange',update);b.removeEventListener('chargingchange',update);};}).catch(()=>{});}
  if(name==='network'){const text=document.createElement('p');text.className='network-state';p.append(text);this.refreshNetwork();const note=document.createElement('p');note.textContent='This reflects browser connectivity. Wi-Fi names and hardware controls are not available.';p.append(note);}
  if(name==='control'){for(const value of ['dark','light','system']){const b=this.button(value[0].toUpperCase()+value.slice(1)+' appearance',()=>{this.wm.updateSettings({appearance:value});this.close();});p.append(b);}for(const [key,label] of [['reducedMotion','Reduce Motion'],['dockAutoHide','Automatically Hide Dock']]){const labelEl=document.createElement('label');const check=document.createElement('input');check.type='checkbox';check.checked=this.wm.settings[key];check.addEventListener('change',()=>this.wm.updateSettings({[key]:check.checked}));labelEl.append(check,document.createTextNode(label));p.append(labelEl);}p.append(this.button('System Settings…',()=>{this.close();this.wm.openApp('settings');}));}
  if(name==='clock')this.calendar(p);p.querySelector('button,input')?.focus();
 }
 refreshNetwork(){const p=this.panel?.querySelector('.network-state');if(p)p.textContent=navigator.onLine?'Online':'Offline';}
 calendar(p){p.querySelector('.calendar')?.remove();const box=document.createElement('section');box.className='calendar';const date=document.createElement('p');date.textContent=new Date().toLocaleString();box.append(date);const nav=document.createElement('div');nav.className='calendar-nav';const label=document.createElement('strong');label.textContent=this.month.toLocaleDateString(undefined,{month:'long',year:'numeric'});nav.append(this.button('Previous month',()=>{this.month=new Date(this.month.getFullYear(),this.month.getMonth()-1,1);this.calendar(p);}),label,this.button('Next month',()=>{this.month=new Date(this.month.getFullYear(),this.month.getMonth()+1,1);this.calendar(p);}));box.append(nav,this.button('Today',()=>{this.month=new Date();this.calendar(p);}));const grid=document.createElement('div');grid.className='calendar-grid';['S','M','T','W','T','F','S'].forEach(s=>{const el=document.createElement('b');el.textContent=s;grid.append(el);});const y=this.month.getFullYear(),m=this.month.getMonth(),start=new Date(y,m,1).getDay(),total=new Date(y,m+1,0).getDate(),today=new Date();for(let i=0;i<start+total;i++){const cell=document.createElement('span');cell.textContent=i<start?'':String(i-start+1);if(i-start+1===today.getDate()&&y===today.getFullYear()&&m===today.getMonth())cell.className='today';grid.append(cell);}box.append(grid);p.append(box);}
 spotlight(){this.menuName=null;const context=this.capture();const p=this.showPanel(null,'spotlight',context);p.setAttribute('role','dialog');p.setAttribute('aria-label','Spotlight');const input=document.createElement('input');input.type='search';input.placeholder='Search apps, files and folders';input.setAttribute('aria-label','Search apps, files and folders');const results=document.createElement('div');results.className='spotlight-results';p.append(input,results);input.addEventListener('input',()=>this.search(input.value));input.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();results.querySelector('button')?.focus();}if(e.key==='Enter'){e.preventDefault();results.querySelector('button')?.click();}});results.addEventListener('keydown',e=>{const list=Array.from(results.querySelectorAll('button'));let i=list.indexOf(document.activeElement);if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();i+=(e.key==='ArrowDown'?1:-1);if(i<0)input.focus();else list[i%list.length]?.focus();}});this.search('');input.focus();}
 search(query){const results=this.panel?.querySelector('.spotlight-results');if(!results)return;results.replaceChildren();const q=query.trim().toLocaleLowerCase();let count=0;const add=(label,run)=>{if(count++>=150)return;results.append(this.button(label,()=>{this.close(false);try{run();}catch(e){this.workspace.report(e.message,true);}}));};for(const app of this.wm.apps||[]){if(app.name.toLocaleLowerCase().includes(q))add(app.name,()=>this.wm.openApp(app.id));}const walk=path=>{for(const node of this.store.list(path)){const full=path.concat(node.name);if(node.name.toLocaleLowerCase().includes(q))add((node.type==='folder'?'Folder: ':'File: ')+this.store.formatPath(full),()=>this.workspace.openPath(full));if(node.type==='folder')walk(full);}};try{walk([]);}catch(e){this.workspace.report(e.message,true);}if(!count){const empty=document.createElement('p');empty.textContent='No matches';results.append(empty);}if(count>150){const note=document.createElement('p');note.textContent='Showing the first 150 matches. Refine your search.';results.append(note);}}
 help(title){let text;if(title==='Keyboard Shortcuts')text='Command/Ctrl+S: Save. Shift+Command/Ctrl+S: Save As. Command/Ctrl+N: New window/document. Shift+Command/Ctrl+N: New folder. Command/Ctrl+W: Close window. Command/Ctrl+Space: Spotlight. F3: Window Overview. Menus: arrows to navigate, Enter to activate, Escape to close. Finder: Enter to open, F2 to rename, Delete to move to Trash.';else if(title==='Storage & Browser Capabilities')text='Files use this browser’s localStorage, v1 format: 1 MB per text file, 4 MB filesystem, 5,000 nodes. Settings and saved workspace use separate versioned keys; Sketch uses IndexedDB. Clearing site data removes these files. Export important documents and drawings. Damaged storage opens read-only; stale tabs cannot overwrite newer data. Clipboard, battery and storage access depend on browser permissions. Safari embeds only HTTP(S) sites; iframe policies may prevent display, and load events cannot prove success. Use Open Externally. No server, cloud sync, real OS shell or Wi-Fi hardware control is provided.';else if(title.startsWith('About '))text=title+' is part of a Monterey-inspired browser desktop. Your files stay in this browser. Finder, TextEdit and Terminal support independent windows. This is a web simulation, not macOS.';else text='Use the Dock to open or return to apps. Finder, TextEdit and Terminal support multiple windows through File or Window. Desktop files share the same filesystem with Finder and Terminal. Double-click files to open; right-click for file actions. TextEdit asks before losing unsaved work. Trash can restore files or permanently empty after confirmation. Spotlight searches apps and all virtual folders. Window Overview restores hidden or minimized windows. Settings and saved documents restore on reload; unsaved drafts do not. Safari’s Home is https://vectorindex.cloud. Sketch saves the latest draft locally; export PNG for backup.';return this.workspace.dialog(title,text,null,[{label:'Close',value:true,primary:true}]);}
}
global.MacMenus=MacMenus;
})(window,window.jQuery);
