'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const {JSDOM}=require('jsdom');
function desktop(saved={}){const dom=new JSDOM(fs.readFileSync('site/index.html','utf8'),{runScripts:'outside-only',url:'https://desktop.test/',pretendToBeVisual:true});const w=dom.window;Object.entries(saved).forEach(([k,v])=>w.localStorage.setItem(k,v));w.matchMedia=()=>({matches:true,addEventListener(){}});w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};w.jQuery=require('jquery')(w);for(const file of ['file-store','terminal','workspace','apps','menus','desktop'])w.eval(fs.readFileSync('site/js/'+file+'.js','utf8'));w.startDesktop();return {w,wm:w.wm,ws:w.workspace,store:w.fileStore,close(){w.clearInterval(w.menus.clockTimer);w.clearTimeout(w.wm.saveTimer);w.workspace.dispose();w.wm.listWindows().forEach(r=>r.controller?.dispose?.());dom.window.close();}};}
const tick=()=>new Promise(r=>setTimeout(r,0));
test('desktop boots local files, creates independent windows and Dock reuses recent',()=>{const x=desktop();try{assert.equal(x.wm.listWindows().length,1);assert.equal(x.w.document.querySelectorAll('#desktop-files .file-item').length,2);const a=x.wm.activeWindow,b=x.wm.openApp('finder',{newWindow:true});a.controller.navigate(['Documents']);b.controller.navigate(['Downloads']);assert.deepEqual(Array.from(a.controller.path),['Documents']);assert.deepEqual(Array.from(b.controller.path),['Downloads']);assert.notEqual(a.id,b.id);assert.equal(x.wm.openApp('finder').id,b.id);assert.equal(x.wm.listWindows().length,2);const t1=x.wm.openApp('terminal',{newWindow:true}),t2=x.wm.openApp('terminal',{newWindow:true});t1.controller.terminal.run('cd /Documents');assert.deepEqual(Array.from(t2.controller.cwd),[]);assert.deepEqual(Array.from(t1.controller.cwd),['Documents']);}finally{x.close();}});
test('same saved file focuses existing editor; separate new documents retain own values',async()=>{const x=desktop();try{await x.ws.openPath(['Documents','notes.txt']);const a=x.wm.activeWindow;await x.ws.openPath(['Documents','notes.txt']);assert.equal(x.wm.activeWindow.id,a.id);const b=x.wm.openApp('textedit',{newWindow:true});a.controller.input('first draft');b.controller.input('second draft');assert.equal(a.controller.editor.content,'first draft');assert.equal(b.controller.editor.content,'second draft');x.ws.dialog=async()=> 'cancel';assert.equal(await x.wm.requestClose(a.id),false);assert.equal(x.wm.listWindows().filter(w=>w.appId==='textedit').length,2);}finally{x.close();}});
test('batch close and restart cancellation preserve all earlier discarded drafts',async()=>{const x=desktop();try{const a=x.wm.openApp('textedit',{newWindow:true}),b=x.wm.openApp('textedit',{newWindow:true});a.controller.input('a');b.controller.input('b');let choices=['discard','cancel'];x.ws.dialog=async()=>choices.shift();assert.equal(await x.wm.closeApp('textedit'),false);assert.equal(a.controller.editor.content,'a');assert.equal(a.controller.editor.dirty,true);assert.equal(x.wm.listWindows().filter(w=>w.appId==='textedit').length,2);choices=['discard','cancel'];assert.equal(await x.wm.restart(),false);assert.ok(x.w.document.getElementById(a.id));assert.ok(x.w.document.getElementById(b.id));}finally{x.close();}});
test('minimize and close activate most recent visible windows; show desktop preserves minimized state',async()=>{const x=desktop();try{const a=x.wm.activeWindow,b=x.wm.openApp('terminal',{newWindow:true}),c=x.wm.openApp('textedit',{newWindow:true});x.wm.minimizeWindow(c.id);assert.equal(x.wm.activeWindow.id,b.id);x.wm.showDesktop();assert.equal(x.wm.activeWindow,null);x.wm.focusWindow(b.id);assert.equal(x.wm.desktopShown,false);assert.equal(a.element.hasAttribute('inert'),false);assert.equal(b.element.hasAttribute('inert'),false);assert.equal(c.element.hasAttribute('inert'),true);assert.equal(c.minimized,true);await x.wm.requestClose(b.id);assert.equal(x.wm.activeWindow.id,a.id);}finally{x.close();}});
test('versioned settings and saved documents restore, unsaved drafts do not',async()=>{let x=desktop(),saved;try{x.wm.updateSettings({appearance:'light',reducedMotion:true,dockAutoHide:true,clock24:true,wallpaper:'ocean'});await x.ws.openPath(['Documents','notes.txt']);const editor=x.wm.activeWindow;editor.controller.input('saved text');await editor.controller.save();editor.bounds={x:200,y:140,width:620,height:420};const unsaved=x.wm.openApp('textedit',{newWindow:true});unsaved.controller.input('do not persist this draft');x.wm.minimizeWindow(editor.id);x.wm.saveSession();saved=Object.fromEntries(Object.keys(x.w.localStorage).map(k=>[k,x.w.localStorage.getItem(k)]));assert.ok(!saved['macos.web.session.v1'].includes('do not persist'));}finally{x.close();}x=desktop(saved);try{assert.equal(x.wm.settings.appearance,'light');assert.equal(x.wm.settings.clock24,true);const editors=x.wm.listWindows().filter(r=>r.appId==='textedit');assert.equal(editors.length,1);assert.equal(editors[0].controller.editor.content,'saved text');assert.equal(editors[0].minimized,true);assert.equal(editors[0].bounds.x,200);}finally{x.close();}});
test('invalid saved paths fall back safely and smaller viewport keeps controls accessible',()=>{const session={version:1,windows:[{appId:'finder',state:{path:['missing']},bounds:{x:2000,y:2000,width:1200,height:800}},{appId:'terminal',state:{path:['missing']},bounds:{x:-10,y:-20,width:600,height:500}},{appId:'textedit',state:{path:['missing.txt']}}]};const x=desktop({'macos.web.session.v1':JSON.stringify(session)});try{Object.defineProperty(x.w,'innerWidth',{value:480,writable:true});Object.defineProperty(x.w,'innerHeight',{value:360,writable:true});x.w.dispatchEvent(new x.w.Event('resize'));assert.equal(x.wm.listWindows().some(r=>r.appId==='textedit'),false);for(const r of x.wm.listWindows()){assert.ok(r.bounds.x>=0);assert.ok(r.bounds.y>=32);assert.ok(r.bounds.x+r.bounds.width<=480);assert.ok(r.bounds.y+r.bounds.height<=360);}assert.deepEqual(Array.from(x.wm.listWindows()[0].controller.path),['Desktop']);}finally{x.close();}});
test('menu New Folder targets active Finder, keyboard save acts once on correct editor',async()=>{const x=desktop();try{const finder=x.wm.activeWindow;finder.controller.navigate(['Downloads']);x.wm.openApp('finder',{newWindow:true,path:['Documents']});x.wm.focusWindow(finder.id);x.wm.workspace.nameDialog=async(title,name,description,create)=>create('scope-test');x.w.menus.openMenu('File',x.w.menus.buttons[2]);x.w.menus.panel.querySelector('[data-command=newFolder]').click();await tick();assert.equal(x.store.read(['Downloads','scope-test']).type,'folder');assert.throws(()=>x.store.read(['Documents','scope-test']));await x.ws.openPath(['Documents','notes.txt']);const editor=x.wm.activeWindow;editor.controller.input('keyboard');editor.controller.textarea[0].focus();let writes=0;const unsubscribe=x.store.subscribe(e=>{if(e.type==='write')writes++;});editor.controller.textarea[0].dispatchEvent(new x.w.KeyboardEvent('keydown',{key:'s',ctrlKey:true,bubbles:true}));await tick();assert.equal(writes,1);unsubscribe();assert.equal(x.store.read(['Documents','notes.txt']).content,'keyboard');}finally{x.close();}});
test('window overview restores minimized target and closes on selection',()=>{const x=desktop();try{const a=x.wm.activeWindow;x.wm.minimizeWindow(a.id);x.wm.overview();const dialog=x.w.document.querySelector('.window-overview');assert.ok(dialog.open);dialog.querySelector('.overview-card').click();assert.equal(x.w.document.querySelector('.window-overview'),null);assert.equal(x.wm.activeWindow.id,a.id);assert.equal(a.minimized,false);}finally{x.close();}});
test('Go menu and opening a Finder path reuse the intended window unless explicitly new',async()=>{const x=desktop();try{const a=x.wm.activeWindow,b=x.wm.openApp('finder',{newWindow:true});x.wm.focusWindow(a.id);x.w.menus.openMenu('Go',x.w.menus.buttons[5]);x.w.menus.panel.querySelector('[data-command=go-Documents]').click();await tick();assert.deepEqual(Array.from(a.controller.path),['Documents']);assert.deepEqual(Array.from(b.controller.path),['Desktop']);assert.equal(x.wm.listWindows().length,2);x.wm.openApp('finder',{path:['Downloads']});assert.equal(x.wm.listWindows().length,2);assert.deepEqual(Array.from(a.controller.path),['Downloads']);}finally{x.close();}});
test('Edit commands never act on text belonging to a different active window',()=>{const x=desktop();try{const finder=x.wm.activeWindow,editor=x.wm.openApp('textedit',{newWindow:true});const el=editor.controller.textarea[0];el.value='protected';el.focus();el.setSelectionRange(0,9);x.wm.focusWindow(finder.id,false);const context=x.w.menus.capture();assert.equal(context.record.id,finder.id);assert.equal(context.element,el);for(const id of ['cut','copy','paste','selectAll','undo','redo'])assert.equal(x.w.menus.canEdit(id,context),false,id);x.wm.focusDesktop();assert.equal(x.w.menus.canEdit('cut',x.w.menus.capture()),false);}finally{x.close();}});
test('opening folders and Reveal in Finder reuse existing Finder windows',async()=>{const x=desktop();try{await x.ws.openPath(['Desktop','Project']);await x.ws.openPath(['Documents']);assert.equal(x.wm.listWindows().filter(r=>r.appId==='finder').length,1);await x.ws.openPath(['Documents','notes.txt']);await x.wm.activeWindow.controller.commands.reveal.run();assert.equal(x.wm.listWindows().filter(r=>r.appId==='finder').length,1);}finally{x.close();}});

test('pointer gestures stop and release capture on modal, focus, blur, hidden page and close interruptions', async () => {
    for (const interruption of ['modal', 'focus', 'blur', 'hidden', 'close']) {
        const x = desktop();
        try {
            const record = x.wm.activeWindow;
            const handle = record.element.querySelector(interruption === 'hidden' ? '.resize-se' : '.window-header');
            let captured = false, releases = 0;
            handle.setPointerCapture = () => { captured = true; };
            handle.hasPointerCapture = () => captured;
            handle.releasePointerCapture = () => { captured = false; releases++; };
            const pointer = (type, px, py) => {
                const event = new x.w.MouseEvent(type, { clientX: px, clientY: py, button: 0, bubbles: true, cancelable: true });
                Object.defineProperty(event, 'pointerId', { value: 12 });
                handle.dispatchEvent(event);
            };
            pointer('pointerdown', 470, 78);
            pointer('pointermove', 490, 98);
            assert.ok(x.wm.activeGesture, interruption + ' starts a gesture');
            const bounds = { ...record.bounds };
            let modal;
            if (interruption === 'modal') {
                modal = x.ws.dialog('Interrupt drag', '', null, [{ label: 'Close', value: true }]);
                await tick();
            } else if (interruption === 'focus') {
                x.w.document.querySelector('[data-menu="Apple"]').focus();
            } else if (interruption === 'blur') {
                x.w.dispatchEvent(new x.w.Event('blur'));
            } else if (interruption === 'hidden') {
                Object.defineProperty(x.w.document, 'visibilityState', { configurable: true, value: 'hidden' });
                x.w.document.dispatchEvent(new x.w.Event('visibilitychange'));
            } else {
                await x.wm.requestClose(record.id);
            }
            pointer('pointermove', 590, 198);
            pointer('pointerup', 590, 198);
            assert.deepEqual({ ...record.bounds }, bounds, interruption + ' freezes the prior bounds');
            assert.equal(x.wm.activeGesture, null, interruption + ' clears the active gesture');
            assert.equal(captured, false, interruption + ' releases capture');
            assert.equal(releases, 1, interruption + ' releases capture once');
            assert.equal(x.w.document.documentElement.classList.contains('window-gesture'), false);
            if (modal) { x.w.document.querySelector('dialog button').click(); await modal; }
        } finally { x.close(); }
    }
});
